version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Nik@D1182098
      MYSQL_DATABASE: grocery_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Nik@D1182098
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/grocery_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nik@D1182098
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
